version: '3'
services:
  frontend:
    image: node:16.16-alpine
    command: sh -c "yarn install; yarn run dev"
    working_dir: /app/frontend/
    volumes:
      - ${PWD}/frontend:/app/frontend
    ports:
      - "80:3000"
  
  server:
    working_dir: /app/backend/
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/srv/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
      
  phpfpm:
    working_dir: /app/backend/
    image: php:7.3-fpm-alpine
    volumes:
      - ./backend:/srv/www